<?php

/**
 * @file
 * Message notify.
 */
use Drupal\Core\Entity\Entity\EntityViewMode;
use Drupal\message_notify\MessageNotify;

/**
 * Implements hook_entity_view_mode_info_alter().
 *
 * Add the notifiers view modes.
 */
function message_notify_entity_view_mode_info_alter(&$view_modes) {
  $notifiers = MessageNotify::Notifiers();

  foreach ($notifiers as $notifier) {
    w$plugin_view_modes = $notifier['view_modes'];

    foreach ($plugin_view_modes as $type => $plugin_view_mode) {

      if (entity_load('entity_view_mode', 'message.' . $type)) {
        // The view mode already exists. Skipping.
        continue;
      }

      /** @var EntityViewMode $view_mode */
      $view_mode = entity_create('entity_view_mode');
      $view_mode
        ->setTargetType('message')
        ->set('label', $plugin_view_mode->render())
        ->set('status', TRUE)
        ->set('id', 'message.' . $type)
        ->save();
    }
  }
}

/**
 * Implements hook_mail().
 *
 * Set's the message subject and body as configured.
 */
function message_notify_mail($key, &$message, $params) {
  // Send the email.
  $message['subject'] = $params['email_subject'];
  $message['body'][] = $params['email_body'];
}
