<?php
/**
 * @file
 * Code for the Message notify example feature.
 */

use Drupal\comment\Entity\Comment;
use Drupal\message\Entity\Message;

/**
 * Implements hook_comment_insert().
 *
 * Send a message to the node author when a new comment is created.
 */
function message_notify_example_comment_insert(Comment $comment) {

  /** @var Drupal\node\Entity\Node $node */
  $node = $comment->getCommentedEntity();

  if ($comment->getOwnerId() == $node->getOwnerId()) {
    // The comment author is also the node author, and we would ususally
    // return early here, but since this is an example, we send an email
    // anyway.
  }

  // Create a new message, assigned to the node author, and add a
  // reference to the comment, so we can later use tokens related to that
  // comment.
  $message = Message::Create(array('type' => 'comment_insert', 'uid' => $node->getOwnerId()));
  $message->set('field_comment_ref', $comment);

  // Send the message.
  message_notify_send_message($message);
}
